title: FIFE Engine
description: FIFE is a multi-platform isometric game engine written in C++
markdown: kramdown
timezone: UTC
future: false
show_drafts: false
permalink: /:title
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
